lab02/calculo/urls.py
from django.urls import path

from . import views

app_name = 'calculo'

urlpatterns = [
    path('', views.index, name='index'),
    path('tarea1/', views.tarea1, name='tarea1'),
    path('tarea2/', views.tarea2, name='tarea2'),
    path('enviar',views.enviar,name='enviar'),
    path('enviar2',views.enviar2,name='enviar2'),
]

lab02/encuesta/urls.py
from django.urls import path

from . import views

app_name = 'encuesta'

urlpatterns = [
    path('', views.index, name='index'),
    path('enviar',views.enviar,name='enviar'),
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('admin/', admin.site.urls),
    path('calculo/', include('calculo.urls')),
    
]

lab02/calculo/models.py
from django.db import models

# Create your models here.

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/calculo/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context={
        'titulo':'Formulario',
    }
    return render(request,'calculo/index.html',context)

def tarea1(request):
    context={
        'titulo':'Tarea1',
    }
    return render(request,'calculo/formulario.html',context)

def tarea2(request):
    context={
        'titulo':'Tarea2',
    }
    return render(request,'calculo/form2.html',context)

def enviar (request):
    num1 = int(request.POST['numero1'])
    num2 = int(request.POST['numero2'])
    operacion= request.POST['operacion']
    signo=''
    if operacion == 'suma':
        resultado = num1 + num2
        signo='+'
    elif operacion == 'resta':
        resultado = num1 - num2
        signo='-'
    elif operacion == 'multiplicacion':
        resultado = num1 * num2
        signo='*'
    elif operacion == 'division':
        resultado = num1 / num2
        signo='/'
    context = {
        'titulo': "Resultado",
        'num1': num1,
        'num2': num2,
        'operacion': request.POST['operacion'],
        'resultado': resultado,
        'signo': signo
    }
    return render (request, 'calculo/respuesta.html', context)
    
def enviar2 (request):
    diam = int(request.POST['diametro'])
    altura = int(request.POST['altura'])
    resultado=3.14*pow((diam/2),2)*altura
    context = {
        'titulo': "CALCULO DEL VOLUMEN DE UN CILINDRO",
        'Diametro': diam,
        'Altura': altura,
        'resultado': resultado,
    }
    return render (request, 'calculo/resultado.html', context)

lab02/encuesta/views.py
from django.shortcuts import render

#Create your views here.

def index(request):
    context={
        'titulo':"Formulario",
    }
    return render(request, 'encuesta/formulario.html', context)


def enviar (request):
    context = {
        'titulo': "Respuesta",
        'nombre': request.POST['nombre'],
        'clave': request. POST['password'],
        'educacion': request. POST['educacion'], 
        'nacionalidad': request. POST['nacionalidad'],
        'idiomas': request.POST.getlist('idiomas'), 
        'correo': request. POST['email'],
        'website': request.POST['sitioweb'],
    }
    return render (request, 'encuesta/respuesta.html', context)

lab02/calculo/templates/calculo/form2.html
<h2>{{ titulo }}</h2>
<form action="{% url 'calculo:enviar2' %}" method="post">
    {%csrf_token %}
    Introduzca el diametro en metros:
    <input type="number" name="diametro" maxlength="4" required><br> 
    introduzca la altura en metros:
    <input type="number" name="altura"maxlength="4" required> <br>
    <input type="submit" name="submit" value="Enviar2">
</form>

lab02/calculo/templates/calculo/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'calculo:enviar' %}" method="post">
    {%csrf_token %}
    Numero1:
    <input type="number" name="numero1" maxlength="4" required><br> 
    Numero2:
    <input type="number" name="numero2"maxlength="4" required> <br>
    Operacion:
    <select name="operacion">
        <option value="suma" selected="selected">Suma</option>
        <option value="resta" >Resta</option> 
        <option value="multiplicacion">Multiplicacion</option> 
        <option value="division">Division</option>
    </select> <br>
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/calculo/templates/calculo/index.html
<h1>Página Principal</h1>
    <p>Haz clic en los siguientes enlaces para ir a otras páginas:</p>
    <ul>
        <li><a href="{% url 'calculo:tarea1' %}">Ir a Tarea 1</a></li>
        <li><a href="{% url 'calculo:tarea2' %}">Ir a Tarea 2 </a></li>
    </ul>

lab02/calculo/templates/calculo/respuesta.html
<h2>{{ titulo }}</h2>

<p>Numero1: {{ num1 }}</p>
<p>Numero2: {{ num2 }}</p>
<p>Operacion: {{ operacion }}</p> 
<p>Resultado: La {{operacion}} de {{num1}}{{signo}}{{num2}}={{resultado}}</p>

lab02/calculo/templates/calculo/resultado.html
<h2>{{ titulo }}</h2>

<p>Diametro: {{ Diametro }}</p>
<p>Altura: {{ Altura }}</p>
<p>El volumen del cilindro es de {{resultado}} metros cubicos</p>

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {%csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br> 
    Contraseña:
    <input type="password" name="password"><br>
    Educacion:
    <select name="educacion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="educacion-obligatoria" selected="selected">Educación Obligatoria</option> 
        <option value="formacion-profesional">Formación profesional</option> 
        <option value="universidad">Universidad</option>
    </select> <br>
    Nacionalidad:
    <input type="radio" name="nacionalidad" value="hispana">Hispana</input>
    <input type="radio" name="nacionalidad" value="otra">Otra</input><br> 
    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
    <input type="checkbox" name="idiomas" value="inglés">Inglés</input> 
    <input type="checkbox" name="idiomas" value="francés">Francés</input>
    <input type="checkbox" name="idiomas" value="aleman">Alemán</input><br> 
    Email:
    <input type="text" name="email"><br>
    Sitio Web:
    <input type="text" name="sitioweb"><br>
    // Botón de enviar
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }}</h2>
<p>Nombre: {{ nombre }}</p>
<p>Clave: {{ clave }}</p>
<p>Educación: {{ educacion }}</p>
<p>Nacionalidad: {{ nacionalidad }}</p> 
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %} 
    <li>{{ item }}</li> 
    {% endfor %}
</ul>
<p>Email: {{ correo }}</p> 
<p>Sitio Web: {{ website }}</p>